In [1]:
import pandas as pd
pd.__version__

'2.2.3'

In [2]:
# numpy 생성
import numpy as np

arr = np.arange(100,105)
arr

array([100, 101, 102, 103, 104])

In [14]:
a = [1,2,3,4]
i = ["1","2","3","4"]
b = pd.Series(data=a, index=i)
print(b)
print(b.iloc[3], b.loc["3"])

1    1
2    2
3    3
4    4
dtype: int64
4 3


In [15]:
b[2]

C:\Users\hi\AppData\Local\Temp\ipykernel_5208\2083252473.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  b[2]


np.int64(3)

In [ ]:
print(b)
c = b[ ["1",'3','2'] ] # 배열한 순서대로 나옴
print(c)

1    1
2    2
3    3
4    4
dtype: int64
1    1
3    3
2    2
dtype: int64


In [20]:
d = np.array(a)
d * 10

array([10, 20, 30, 40])

In [24]:
b[b > 3]

4    4
dtype: int64

In [26]:
b.index
b.values

array([1, 2, 3, 4])

In [38]:
b.index  = [5,'4',3,True]
b[True]

np.int64(4)

In [ ]:
b.ndim
b.shape
b["2"] = np.nan

In [50]:
b[b.notnull()]

5       1.0
4       2.0
3       3.0
True    4.0
dtype: float64

In [51]:
b["4":True]

4       2.0
3       3.0
True    4.0
dtype: float64

In [86]:
# dtype은 float32가 되도록 생성하세요

a1 = [3, 5, 7, 9, 11]
b = pd.Series(a1, dtype='float32')

b

0     3.0
1     5.0
2     7.0
3     9.0
4    11.0
dtype: float32

In [55]:
a2 = ['가','나','다','라','마']
pd.Series(a2)

0    가
1    나
2    다
3    라
4    마
dtype: object

In [64]:
sample = pd.Series([10,20,30,40,50], ['가','나','다','라','마'])
sample

가    10
나    20
다    30
라    40
마    50
dtype: int64

In [67]:
sample[["나","라"]]

나    20
라    40
dtype: int64

In [ ]:
np.random.seed(20)
sample2 = pd.Series(np.random.randint(100, 200, size=(15,)))
sample2[sample2 <= 160]

2     115
4     128
6     109
7     120
9     122
11    134
13    140
dtype: int32

In [73]:
sample2[(130 <= sample2) & (sample2 <= 170)]

11    134
13    140
dtype: int32

In [74]:
sample3 = pd.Series(['apple', np.nan, 'banana', 'kiwi', 'gubong'],
                    ['가', '나', '다', '라', '마'])
sample3

가     apple
나       NaN
다    banana
라      kiwi
마    gubong
dtype: object

In [76]:
sample4 = pd.Series(['IT서비스', np.nan, '반도체', np.nan, '바이오', '자율주행'])
sample4[sample4.isnull()]

1    NaN
3    NaN
dtype: object

In [77]:
sample4[sample4.notnull()]

0    IT서비스
2      반도체
4      바이오
5     자율주행
dtype: object

In [79]:
np.random.seed(0)
sample = pd.Series(np.random.randint(100, 200, size=(10,)))
sample[2:7]

2    164
3    167
4    167
5    109
6    183
dtype: int32

In [81]:
np.random.seed(0)
sample2 = pd.Series(np.random.randint(100, 200, size=(10,)), index=list('가나다라마바사아자차'))
sample2
sample2['바':'차']

바    109
사    183
아    121
자    136
차    187
dtype: int32

In [82]:
sample2['가':'다']

가    144
나    147
다    164
dtype: int32

In [83]:
sample2['나':'바']

나    147
다    164
라    167
마    167
바    109
dtype: int32